import Head from 'next/head'
import About from '../components/About/About'
import Contact from '../components/Contact/Contact'
import Hero from '../components/Hero/Hero'
import Layout from '../components/Layout/Layout'
import Portfolio from '../components/Portfolio/Portfolio'
import Skills from '../components/Skills/Skills'

export default function Home() {
  return (
    <>
      <Head>
        <title>React Next TypeScript Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg" sizes="32x32" href="/img/logo.svg" />
      </Head>
      <Layout>
        <main>
          <Hero />
          <About />
          <Skills />
          <Portfolio />
          <Contact />
        </main>
      </Layout>
      <div className="background-animation">
        <div id="ball-one"></div>
        <div id="ball-two"></div>
        <div id="ball-three"></div>
      </div>
    </>
  )
}
